server:
  port: 8081

spring:
  application:
    name: backend

backend:
  security:
    users:
      - username: testUser
        password: $2a$10$uKw9ORqCF.qA3p6woHCgmeGW0jFuU9AstYhl61Uw8RTQ5AaZCfuru
        roles: USER
  measurements:
    ttlInSeconds: 2592000 # (in seconds) 30 days

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus", "health" ]

aws:
#  region: eu-central-1
#  dynamodb:
#    endpoint: http://localhost:8000
#    accessKey: dummyAccess
#    secretKey: dummySecret
#
#notification:
#  topicarn: dummy